- name: Install nginx
  ansible.builtin.package:
    name:
      - "{{ nginx_package }}"

- name: Copy nginx configuration
  ansible.builtin.template:
    src: "{{ nginx_config }}"
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: preserve
  notify: Restart nginx
